# 异常

## 1. 什么是异常

Java 中处理错误的一种机制，Java 中的错误大致分为两类，一类是编译时错误，一般是指语法错误（低级错误，很容易发现，一般不会犯的），编译无法通过。

另一类是运行时错误，编译可以正常通过，但是运行时报错，不是语法错误，是业务逻辑的错误，编写代码和程序编译期间难以发现，不容易发现，数组下标越界，0 作为除数。

Java 是面向对象的编程语言，Java 中的任何事物都应该以对象的形式来呈现，错误也不例外，要有对象就必须先有类，Java 中就应该有专门用来描述错误的类，这些类就是异常类。

```
 * 事物执行过程中，可能会抛异常,如果当时未捕获异常，直接抛出，则不执行异常后面的代码
 * 如果捕获异常，会执行后面的代码
```

Java 结合异常类提供了处理错误的机制，具体步骤：

1、当检测到程序出现错误，Java 会自动创建一个包含错误信息的异常对象。

2、将异常对象提交给系统。

3、由系统将该对象抛给能够处理的代码(对象)进行处理。

异常可以分为两大类：

- Error
- Exception

Error 指系统错误，由 JVM 生成，我们编写的程序无法处理。

Exception 指程序运行期间出现的错误，我们编写的程序可以进行处理。

## 2. 异常的使用

try-catch，try 用来监听可能会抛出异常的代码，catch 用来捕获系统抛出的异常。

```java
try{
	//代码（有可能会抛出异常）
} catch(Exception e){
	e就是异常对象
	//进行处理
}
```

实际开发中并不是每行代码都需要自己去写 try-catch，因为 JVM 已经提供了自动捕获异常的机制。

JVM 可以自动，那么我们就不需要手动捕获了，但是不建议这样做，因为这样的话 JVM 的压力过大。

可能会抛出异常的代码，我们需要手动进行 try-catch，一般不太会出现问题的代码，不需要手动 try-catch。·

```java
try{

}catch(Excetion e){

}finally{
	
}
```

finally 的作用无论程序是否抛出异常，finally 代码块中的程序都会执行，所以一般将释放资源的代码写到 finally 中。

多态的应用：

方法定义时，形参定义为父类，真正在调用的时候传入子类对象

## 3. 异常类

Java 将运行时出现的错误全部封装成类，并且不是一个类而是一组有层级关系的类。

最顶层是 Throwable，是所有异常类的根节点，Throwable 有两个直接子类 Error 和 Exception。

第一层 Throwable

第二层 Error（Throwable 派生的）

第三层 AWTError、IOError、VirtualMachineError（Error 派生的）

第四层 StackOverFlowError、OutOfMemoryError（VirtualMachineError 派生的）

第二层 Exception（Throwable 派生的）

第三层 IOException、RuntimeException（Exception 派生的）

第四层 FileLockInterruptException、FileNotFondException、FilerException（IOException 派生的）

第四层 ArithmeticException、ClassNotException、IllegalArgumentException、ArrayIndexOutOfBoundsException、NullPointException、NoSuchMethodExcpetion、NumberFormatException（RuntimeException 派生的）

## 4. throw 和 throws

throw 和 throws 是 Java 在处理异常时使用的两个关键字，都用来抛出异常，但是使用的方式和表示的含义完全不同。

Java 中抛出异常共有 3 种方式：

1、try-catch，JVM 负责创建并抛出异常，代码可能会抛出异常，也有可能不抛，如果抛出则捕获进行处理。

2、throw，开发者主动创建并抛出异常，执行 throw 关键字的时候就会创建一个异常并且抛出。

```java
package demo8;

public class Test {
    public static void main(String[] args) {
        try {
            String str = "abc";
            if(str.equals("abc")){
                throw new NumberFormatException("无法将字符串转为数字");
            }else{
                System.out.println(Integer.parseInt(str));
            }
        } catch (NumberFormatException e) {
            System.out.println("发生异常");
        }
    }
}
```

3、throws

try-catch、throw 都是作用于具体的逻辑代码，throws 不是作用于逻辑代码的，而是作用于方法，用来描述方法可能会抛出的异常。

```java
package demo8;

public class Test2 {
    public static void test() throws NumberFormatException{
        String str = "abc";
        Integer.parseInt(str);
    }

    public static void main(String[] args) {
        test();
    }
}
```

如果方法 throws RuntimeException 以及它的子类，则方法的调用者不必手动处理异常。如果方法 throws Exception 以及它的除了 RuntimeException 之外的其他子类异常，则方法的调用者必须手动处理该异常，

## 5. 自定义异常

在实际开发中，我们除了使用 Java 提供的异常类之外，也可以根据需求来自定义异常类。

比如：定义一个方法，对传入的参数进行 ++ 操作并返回，同时要求参数必须是整型，如果传入的参数不是整型则抛出异常。

```java
package demo9;

public class MyNumberException extends RuntimeException {
    public MyNumberException() {
    }

    public MyNumberException(String message) {
        super(message);
    }
}
```

```java
package demo9;

public class Test {
    public static void main(String[] args) {
        Test test = new Test();
        System.out.println(test.add("123"));
    }

    public int add(Object object) {
        //判断object类型？
        if(!(object instanceof Integer)){
            String str = "传入的参数不是整数类型";
            throw new MyNumberException(str);
        }else{
            return (Integer)object;
        }
    }
}
```

## 6. ConcurrentModificationException 并发修改异常

```java
public class Test {
    public static void main(String[] args) {
        List<String> list = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            new Thread(()->{
                try {
                    TimeUnit.SECONDS.sleep(1);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                list.add("a");
                System.out.println(list);
            }).start();
        }
    }
}
```

ArrayList 是线程不安全的，多线程并发访问会导致数据错误。

解决办法：

1、将 ArrayList 替换成线程安全的 Vetor。

ArrayList 的 add 方法线程不安全

```java
public boolean add(E e) {
    modCount++;
    add(e, elementData, size);
    return true;
}
```

Vetor 的 add 方法线程安全

```java
public synchronized boolean add(E e) {
    modCount++;
    add(e, elementData, elementCount);
    return true;
}
```

2、使用 Collections.synchronizedList

```java
public class Test {
    public static void main(String[] args) {
        List<String> list = Collections.synchronizedList(new ArrayList<>());
        for (int i = 0; i < 10; i++) {
            new Thread(()->{
                try {
                    TimeUnit.SECONDS.sleep(1);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                list.add("a");
                System.out.println(list);
            }).start();
        }
    }
}
```

3、JUC CopyOnWriteArrayList

```java
public class Test {
    public static void main(String[] args) {
        List<String> list = new CopyOnWriteArrayList<>();
        for (int i = 0; i < 10; i++) {
            new Thread(()->{
                try {
                    TimeUnit.SECONDS.sleep(1);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                list.add("a");
                System.out.println(list);
            }).start();
        }
    }
}
```

CopyOnWriteArrayList，CopyOnWrite 写时复制，当我们往一个容器中添加元素的时候，不直接往当前容器中添加，而是先将当前容器进行 Copy，复制出一个新的容器，往新的容器中添加数据，添加完成之后，再将原容器的引用指向新的容器。

```java
//获取容器
Object[] es = getArray();
//获取容器的长度
int len = es.length;
//复制容器，长度+1
es = Arrays.copyOf(es, len + 1);
//在容器的末尾添加新元素
es[len] = e;
//返回新的容器
setArray(es);
```

要实现读写分离

